---
name: SimpleHeal
api: 4.0.0
version: 2.0.0
main: Electro\SimpleHeal\Main
author: Electro
description: Heals yourslef or others to max health

commands:
 heal:
  description: Heal yourslef or others to max health
  permission: simpleheal.use
permissions:
  simpleheal.use:
    description: Permission to heal yourself or others
    default: op
...
